"""
hexstrike_cache.py — HexStrike Results Caching to Obsidian Vault

Automatically saves HexStrike job results to Obsidian with:
  - Organized folder structure
  - Rich metadata and formatting
  - Search indexing
  - Result aggregation
"""

import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class HexStrikeVaultCache:
    """
    Manages caching of HexStrike results in Obsidian Vault.
    
    Structure:
        HexStrike/
        ├── Jobs/
        │   ├── 2026-02-19/
        │   │   ├── job-uuid-1.md
        │   │   └── job-uuid-2.md
        │   └── 2026-02-20/
        ├── Tools/
        │   ├── nmap.md
        │   └── nuclei.md
        └── Summaries/
            └── weekly-02-19.md
    """

    def __init__(self, vault_client=None):
        """
        Initialize cache.
        
        Args:
            vault_client: ObsidianVaultClient instance
        """
        self.vault_client = vault_client
        self.cache_root = "HexStrike"

    def cache_job_result(
        self,
        task_id: str,
        tool: str,
        params: Dict[str, Any],
        result: Dict[str, Any],
        job_id: Optional[str] = None,
        execution_time: Optional[float] = None,
        error: Optional[str] = None,
    ) -> bool:
        """
        Cache a HexStrike job result to Obsidian.
        
        Args:
            task_id: Task identifier
            tool: Tool name
            params: Tool parameters
            result: Job result data
            job_id: HexStrike job ID
            execution_time: Execution duration in seconds
            error: Error message if any
            
        Returns:
            True if successful
        """
        if not self.vault_client:
            logger.warning("Vault client not configured, skipping cache")
            return False
        
        try:
            now = datetime.now()
            date_str = now.strftime("%Y-%m-%d")
            
            # Prepare metadata
            metadata = {
                "task_id": task_id,
                "tool": tool,
                "job_id": job_id or "unknown",
                "timestamp": now.isoformat(),
                "execution_time_seconds": execution_time or 0,
            }
            
            # Build note content
            content = self._build_job_note(
                tool=tool,
                metadata=metadata,
                params=params,
                result=result,
                error=error,
                execution_time=execution_time,
            )
            
            # Save to vault
            note_path = f"{self.cache_root}/Jobs/{date_str}/{task_id}.md"
            self.vault_client.create_note(note_path, content)
            
            logger.info(f"Cached job result: {note_path}")
            
            # Update tool summary
            self._update_tool_summary(tool, date_str, result, execution_time)
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to cache result: {e}")
            return False

    def _build_job_note(
        self,
        tool: str,
        metadata: Dict[str, Any],
        params: Dict[str, Any],
        result: Dict[str, Any],
        error: Optional[str],
        execution_time: Optional[float],
    ) -> str:
        """Build a formatted job note"""
        
        frontmatter = {
            "tool": metadata["tool"],
            "task_id": metadata["task_id"],
            "job_id": metadata["job_id"],
            "timestamp": metadata["timestamp"],
            "tags": ["hexstrike", f"hexstrike/{metadata['tool'].lower()}"],
        }
        
        content = f"""---
{json.dumps(frontmatter, indent=2)}
---

# HexStrike Job Result: {tool.upper()}

**Task ID**: `{metadata['task_id']}`
**Job ID**: `{metadata['job_id']}`
**Timestamp**: {metadata['timestamp']}

## Execution
- **Tool**: {tool}
- **Duration**: {f'{execution_time:.2f}s' if execution_time else 'N/A'}

## Parameters
```json
{json.dumps(params, indent=2)}
```

## Result
"""
        
        if error:
            content += f"""
### ⚠️ Error
```
{error}
```
"""
        else:
            if result:
                # Format result based on tool type
                if isinstance(result, dict):
                    content += f"""
```json
{json.dumps(result, indent=2)}
```
"""
                elif isinstance(result, list):
                    content += f"""
**Count**: {len(result)}

```json
{json.dumps(result[:100], indent=2)}
```
"""
                else:
                    content += f"""
```
{str(result)[:5000]}
```
"""
            else:
                content += "\nNo result data.\n"
        
        # Add tool documentation link
        content += f"""

## Related
- [[{self.cache_root}/Tools/{tool.lower()}|Tool: {tool}]]

---
*Cache generated by Ascended33 HexStrike Integration*
"""
        
        return content

    def _update_tool_summary(
        self,
        tool: str,
        date_str: str,
        result: Dict[str, Any],
        execution_time: Optional[float],
    ):
        """Update tool summary statistics"""
        try:
            tool_path = f"{self.cache_root}/Tools/{tool.lower()}.md"
            
            # Try to read existing summary
            summary = self.vault_client.read_note(tool_path)
            
            if not summary:
                # Create new summary
                summary = self._create_tool_summary(tool)
            
            # Update stats (this is simplified; full implementation would parse and update)
            # For now, just log that we would update
            logger.debug(f"Would update summary for tool: {tool}")
            
        except Exception as e:
            logger.debug(f"Could not update tool summary: {e}")

    def _create_tool_summary(self, tool: str) -> str:
        """Create a new tool summary page"""
        return f"""# HexStrike Tool: {tool.upper()}

## Description
Tool documentation and usage: `{tool}`

## Recent Jobs
Jobs using this tool will be listed below.

## Statistics
- Total runs: 0
- Success rate: 0%
- Average duration: 0s

---
*Auto-generated by Ascended33 HexStrike Integration*
"""

    def get_cached_results(
        self,
        tool: Optional[str] = None,
        days: int = 7,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve cached results.
        
        Args:
            tool: Filter by tool name (optional)
            days: Look back N days
            
        Returns:
            List of result metadata
        """
        try:
            results = []
            start_date = datetime.now() - timedelta(days=days)
            
            # This would require implementing directory listing in vault_client
            # For now, return empty list
            logger.info(f"Would retrieve cached results for {tool or 'all'} from last {days} days")
            
            return results
            
        except Exception as e:
            logger.error(f"Failed to retrieve cached results: {e}")
            return []

    def create_weekly_summary(self, week_start: Optional[datetime] = None) -> bool:
        """
        Create a weekly summary of all HexStrike jobs.
        
        Args:
            week_start: Start of week (defaults to this week)
            
        Returns:
            True if successful
        """
        if not self.vault_client:
            return False
        
        try:
            if week_start is None:
                today = datetime.today()
                week_start = today - timedelta(days=today.weekday())
            
            week_end = week_start + timedelta(days=6)
            date_str = week_start.strftime("%Y-%m-%d")
            
            # Build summary (simplified)
            content = f"""# HexStrike Weekly Summary

**Week of {week_start.strftime('%Y-%m-%d')} to {week_end.strftime('%Y-%m-%d')}**

## Summary
- Total jobs: 0
- Successful: 0
- Failed: 0

## Tools Used
- (None yet)

## Top Results
- (Pending)

---
*Generated: {datetime.now().isoformat()}*
"""
            
            summary_path = f"{self.cache_root}/Summaries/weekly-{date_str}.md"
            self.vault_client.create_note(summary_path, content)
            
            logger.info(f"Created weekly summary: {summary_path}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to create summary: {e}")
            return False


def get_cache_manager(vault_client=None) -> HexStrikeVaultCache:
    """Get cache manager instance"""
    return HexStrikeVaultCache(vault_client)
